[theme]
primaryColor = "#1D1D1B"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#333333"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
